name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    branches:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10    
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Branch name
        uses: nelonoel/branch-name@v1
        run: echo ${BRANCH_NAME}
        # run: echo running on branch ${GITHUB_REF##*/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ BRANCH_NAME }}
          release_name: Release ${{ BRANCH_NAME }}
          body_path: docs/release_notes.md
          draft: false
          prerelease: false
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: mattyweb/prefectpoc/311data
          tag_with_ref: true
      # - name: Build
      #   run: docker build -t tedmiston/tag-example:${GITHUB_REF##*/} .
