name: Create Release
on:
  push:
    # Sequence of patterns matched against refs/tags
    branch:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10    
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: docs/release_notes.md
          draft: false
          prerelease: false
      # - name: Build
      #   run: docker build -t tedmiston/tag-example:${GITHUB_REF##*/} .
